import { surfaces } from './surfaces.jsx'

/*
  Films — the Letterboxd review diary, rendered from src/films/diary.json
  (generated by `npm run diary`; gitignored until publishing it is a
  deliberate act, same rule as posts).

  HOW TO READ THIS FILE
  §1 · loading a file that may not exist
  §2 · rendering the review text (inline HTML, parity dispatch)
  §3 · the list itself + per-film surfaces

  §1 · A plain `import diary from './diary.json'` would make the BUILD
  fail on any machine where the pipeline hasn't run — the file is
  generated and gitignored. import.meta.glob treats "zero matching
  files" as an empty object instead of an error, so the site renders a
  gentle instruction rather than refusing to compile. Same idiom as
  posts.js loading the posts folder.
*/
const found = import.meta.glob('./diary.json', { eager: true, import: 'default' })
const diary = Object.values(found)[0] ?? null

/*
  §2 · Review text arrives as paragraphs of plain text with a tiny,
  closed set of inline HTML from Letterboxd: <i>, <b>, one <a>. We
  cannot hand strings with tags to React (it would escape them — by
  design; that's the XSS defense), so we convert the known tags to
  elements ourselves.

  Same split-with-capturing-regex idiom as writing/markdown.jsx: a
  regex with ONE capture group makes String.split alternate between
  plain text (even indexes) and matches (odd indexes). Parity — not
  guessing at prefixes — decides how each piece is treated.
*/
const INLINE = /(<i>[^<]*<\/i>|<b>[^<]*<\/b>|<a href="[^"]*"[^>]*>[^<]*<\/a>)/g

function renderInline(text) {
  return text.split(INLINE).map((piece, i) => {
    if (i % 2 === 0) return piece
    if (piece.startsWith('<i>')) return <i key={i}>{piece.slice(3, -4)}</i>
    if (piece.startsWith('<b>')) return <b key={i}>{piece.slice(3, -4)}</b>
    const href = piece.match(/href="([^"]*)"/)?.[1] ?? ''
    const label = piece.match(/>([^<]*)</)?.[1] ?? href
    // only real web links become anchors; anything else stays inert text
    return href.startsWith('http') ? <a key={i} href={href}>{label}</a> : label
  })
}

function Paragraph({ text }) {
  // one paragraph-level tag exists in the data: <blockquote>
  if (text.startsWith('<blockquote>')) {
    const inner = text.replace(/<\/?blockquote>/g, '').trim()
    return <blockquote>{renderInline(inner)}</blockquote>
  }
  return <p>{renderInline(text)}</p>
}

/* Letterboxd's own vocabulary: whole stars, then a half. 4.5 → ★★★★½ */
function stars(rating) {
  return '★'.repeat(Math.floor(rating)) + (rating % 1 ? '½' : '')
}

/* §3 · The list. Each entry may additionally carry an expressive
   surface — looked up by "Title (Year)" in surfaces.jsx. */
export default function Films() {
  if (!diary) {
    return (
      <section className="films" aria-label="film diary">
        <p className="pend">film diary not built yet — run `npm run diary`</p>
      </section>
    )
  }

  return (
    <section className="films" aria-label="film diary">
      <ul className="films-list">
        {diary.map((entry, i) => {
          const Surface = surfaces[`${entry.title} (${entry.year})`]
          return (
            <li key={i} className="film-entry">
              <div className="film-head">
                <span className="film-title">{entry.title}</span>
                <span className="film-year">{entry.year}</span>
                {entry.rating != null && (
                  <span className="film-rating">{stars(entry.rating)}</span>
                )}
                {entry.rewatch && <span className="film-rewatch">rewatch</span>}
                <span className="film-date">{entry.watchedDate}</span>
              </div>
              {entry.review && (
                <div className="film-review">
                  {entry.review.map((p, j) => <Paragraph key={j} text={p} />)}
                </div>
              )}
              {Surface && <Surface entry={entry} />}
            </li>
          )
        })}
      </ul>
    </section>
  )
}
